import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from './model/BootstrapClient.js';
import './globals.scss'
import Navbar from './component/navbar/page.jsx';
import './component/navbar/_navbar.scss'
import Footer from './component/footer/page.jsx';
import './component/footer/_footer.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  // navbar
  


  return (
    <html lang="en">
      <body className={inter.className}>

        

        {children}
        <BootstrapClient />


        <Footer
          copy={`2024 contruccion ©©`}
          ciudad={"suchitoto carretera hacia aguilares"}
          estado={"Cuscatlan El Salvador"}
          contactos="Contacto Ejemplo"
          emai="correo@example.com"
          servicios1="Servicios 1"
          textos1={["Texto 1a", "Texto 1b", "Texto 1c"]}
          servicios2="Servicios 2"
          textos2={["Texto 2a", "Texto 2b", "Texto 2c"]}
          servicios3="Servicios 3"
          textos3={["Texto 3a", "Texto 3b", "Texto 3c"]}
        />
      </body>
    </html>
  )
}
